# kahnchana/pytorch:rfs
FROM pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime

ENV HOME /home/kanchanaranasinghe

RUN pip install numpy~=1.18.5
RUN pip install tqdm~=4.54.0
RUN pip install scipy~=1.5.4
RUN pip install scikit-learn~=0.23.2
RUN pip install pillow~=8.0.1
RUN pip install matplotlib~=3.3.3
RUN pip install tensorboard-logger~=0.1.0
RUN pip install wandb